channels:
  - conda-forge
dependencies:
  - affine=2.4
  - appnope=0.1
  - asttokens=2.2
  - attrs=23.1
  - aws-c-auth=0.7
  - aws-c-cal=0.6
  - aws-c-common=0.8
  - aws-c-compression=0.2
  - aws-c-event-stream=0.3
  - aws-c-http=0.7
  - aws-c-io=0.13
  - aws-c-mqtt=0.8
  - aws-c-s3=0.3
  - aws-c-sdkutils=0.1
  - aws-checksums=0.1
  - aws-crt-cpp=0.20
  - aws-sdk-cpp=1.10
  - backcall=0.2
  - backports=1.0
  - backports.functools_lru_cache=1.6
  - blosc=1.21
  - boost-cpp=1.78
  - branca=0.6
  - brotli=1.0
  - brotli-bin=1.0
  - brotli-python=1.0
  - bzip2=1.0
  - c-ares=1.19
  - ca-certificates=2023.7
  - cairo=1.16
  - certifi=2023.7
  - cfitsio=4.2
  - charset-normalizer=3.2
  - click=8.1
  - click-plugins=1.1
  - cligj=0.7
  - comm=0.1
  - contourpy=1.1
  - curl=8.2
  - cycler=0.11
  - debugpy=1.6
  - decorator=5.1
  - executing=1.2
  - expat=2.5
  - fiona=1.9
  - folium=0.14
  - freetype=2.12
  - freexl=1.0
  - gdal=3.7
  - geopandas=0.13
  - geopandas-base=0.13
  - geos=3.11
  - geotiff=1.7
  - gettext=0.21
  - giflib=5.2
  - hdf4=4.2
  - hdf5=1.14
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.8
  - importlib_metadata=6.8
  - ipykernel=6.24
  - ipython=8.14
  - jedi=0.18
  - jinja2=3.1
  - joblib=1.3
  - json-c=0.16
  - jupyter_client=8.3
  - jupyter_core=5.3
  - kealib=1.5
  - kiwisolver=1.4
  - krb5=1.21
  - lcms2=2.15
  - lerc=4.0
  - libaec=1.0
  - libarchive=3.6
  - libblas=3.9
  - libbrotlicommon=1.0
  - libbrotlidec=1.0
  - libbrotlienc=1.0
  - libcblas=3.9
  - libcurl=8.2
  - libcxx=16.0
  - libdeflate=1.18
  - libedit=3.1
  - libev=4.33
  - libexpat=2.5
  - libffi=3.4
  - libgdal=3.7
  - libglib=2.76
  - libiconv=1.17
  - libjpeg-turbo=2.1.1
  - libkml=1.3
  - liblapack=3.9
  - libnetcdf=4.9
  - libnghttp2=1.52
  - libopenblas=0.3
  - libpng=1.6
  - libpq=15.3
  - librttopo=1.1
  - libsodium=1.0
  - libspatialindex=1.9
  - libspatialite=5.0
  - libsqlite=3.42
  - libssh2=1.11
  - libtiff=4.5
  - libwebp-base=1.3
  - libxcb=1.15
  - libxml2=2.11
  - libzip=1.9
  - libzlib=1.2
  - llvm-openmp=16.0
  - lz4-c=1.9
  - lzo=2.10
  - mapclassify=2.5
  - markupsafe=2.1
  - matplotlib=3.7
  - matplotlib-base=3.7
  - matplotlib-inline=0.1
  - munch=4.0
  - munkres=1.1
  - ncurses=6.4
  - nest-asyncio=1.5
  - networkx=3.1
  - nspr=4.35
  - nss=3.89
  - numpy=1.25
  - openjpeg=2.5
  - openssl=3.1
  - packaging=23.1
  - pandas=2.0
  - parso=0.8
  - pcre2=10.40
  - pexpect=4.8
  - pickleshare=0.7
  - pillow=10.0
  - pip=23.2
  - pixman=0.40
  - platformdirs=3.9
  - pooch=1.7
  - poppler=23.05
  - poppler-data=0.4
  - postgresql=15.3
  - proj=9.2
  - prompt-toolkit=3.0
  - prompt_toolkit=3.0
  - psutil=5.9
  - pthread-stubs=0.4
  - ptyprocess=0.7
  - pure_eval=0.2
  - pygments=2.15
  - pyparsing=3.0
  - pyproj=3.6
  - pysocks=1.7
  - python=3.11
  - python-dateutil=2.8
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3
  - pyzmq=25.1
  - rasterio=1.3
  - readline=8.2
  - requests=2.31
  - rtree=1.0
  - scikit-learn=1.3
  - scipy=1.11
  - setuptools=68.0
  - shapely=2.0
  - six=1.16
  - snappy=1.1
  - snuggs=1.4
  - sqlite=3.42
  - stack_data=0.6
  - threadpoolctl=3.2
  - tiledb=2.13
  - tk=8.6
  - tornado=6.3
  - traitlets=5.9
  - typing-extensions=4.7
  - typing_extensions=4.7
  - tzcode=2023c
  - tzdata=2023c
  - urllib3=2.0
  - wcwidth=0.2
  - wheel=0.40
  - xerces-c=3.2
  - xorg-libxau=1.0
  - xorg-libxdmcp=1.1
  - xyzservices=2023.7
  - xz=5.2
  - zeromq=4.3
  - zipp=3.16
  - zlib=1.2
  - zstd=1.5
